aliases: []
creation_timestamp: 1771297958262
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1771297958262
metrics: null
model_id: ''
name: FraudDetectionModel
params: null
run_id: b8d3042c5dc44bca8e014966bdd6464d
run_link: ''
source: models:/FraudDetectionModel/3
status: READY
status_message: null
storage_location: file:///Users/kruthikishore/ml-k8s-project/model/mlruns/866196050669757937/models/m-0f3e339a101a4ddebd973d5f25397819/artifacts
user_id: null
version: 4
